Added more info of actions that invalidate cache
OutSystems/docs-product pull request #163
Opened 2021-03-16 17:57 UTC by aabramos

According to tickets #2218315 and #2037162.

2021-05-18 12:00 UTC, joaorosado commented
I don't agree with this change at all.
If some actions do invalidate explicitly it should be said on the particular action description. Never maintained here on a generic document about caching.

Also saying "or the **HTTPRequestHandler** extension" is just wrong. I don't even know any action from there that actually does it (also did a quick search and did not find any obvious one and the support tickets do not mention any action).

2021-05-19 10:10 UTC, pjft commented
We should then update https://github.com/OutSystems/docs-product/blob/master/src/ref/apis/auto/includejavascript-api.md according to that information - if it does invalidate the cache, we should state where, when and how in that document.

Same for https://github.com/OutSystems/docs-product/blob/master/src/ref/apis/auto/httprequesthandler-api.md - and subsequent action descriptions in Service Studio.

2022-04-18 11:53 UTC, fmrodrigues commented on src/develop/data/caching.md
> +There is a specific cache for each tenant in the multitenant apps, which only stores data related to it. You can invalidate the cache in the multitenant environments by using [System Actions](../../r
@OutSystems/rd-o11-platform-backend-team Can you please review this?

2022-04-20 09:57 UTC, joaorosado requested changes
As I had said before on my previous comment, I don't think this change should be done.

- This page should not have specific mentions of actions that do invalidates as side effects
- The IncludeJavascript_API can have it mentioned on it's own page, if the actions descriptions also get changed to mention it.
- The information about HTTPRequestHandler is just wrong. No action there does cache invalidations.

2022-04-20 10:12 UTC, zohav commented
Our R&D team has reviewed your suggestions and has decided not to include them. We are closing your pull request.

Thank you for your efforts to improve our documentation.

2022-04-20 10:12 UTC, closed without merging