Added import record procedure
OutSystems/docs-product pull request #237
Opened 2022-02-03 00:41 UTC by aabramos

Customers are not aware that, after converting an Entity to a Static Entity, they can also import the records from the database as static records.

2022-04-18 15:39 UTC, carlosrijo requested changes

2022-04-18 15:39 UTC, carlosrijo commented on src/develop/data/modeling/entity.md
> +* The records from the database can be imported as static records. To import the database records, right-click on the Entity, access to the Edit Entity menu item and then select "Import from Database
To keep it coherent I would switch:
> right-click on the Entity
to:
> right-click on the Static Entity

2022-04-18 15:39 UTC, carlosrijo commented on src/develop/data/modeling/entity.md
> +* The database records from the won't be available through database queries, via Aggregate or SQL Query
I don't have historical context on whether this should work or not but I did some testing and I observed Aggregates and SQL Queries keep working after an entity is converted.

2022-04-19 08:29 UTC, zohav commented
Improvements you made have been incorporated in a separate pull request because of a major restructuring of the technical knowledge portfolio. Your pull request is being closed. Thank you for your contribution.

2022-04-19 08:29 UTC, closed without merging

2022-04-19 09:40 UTC, carlosrijo commented
> Improvements you made have been incorporated in a separate pull request because of a major restructuring of the technical knowledge portfolio. Your pull request is being closed. Thank you for your contribution.

Mind sharing the link of the pull request please?