Update network-requirements.md
OutSystems/docs-product pull request #280
Opened 2022-09-16 07:38 UTC by aduarteoutsystems

Added a piece of explicit information that 12000+2 ports should NOT be open to the outside world.
 Separated the relevant ports to access the applications and added the explicit information of the source coming traffic

2022-09-16 07:39 UTC, aduarteoutsystems commented
I read, understood and accept the OutSystems CLA

2022-10-11 11:48 UTC, fmalheiro requested changes

2022-10-11 11:48 UTC, fmalheiro commented on src/setup-maintain/setup/network-requirements.md
> +> **Security Tips**: Those ports shouldn't be open to the internet.
Consider removing the "Open Ports" section, as that information is already further down in subsequent tables.

The "Security Tip" is indeed helpful, but could be also "nearer" to the same tables - as it applies to all the ports mentioned there.

2022-10-11 13:18 UTC, fmalheiro approved these changes

2022-10-11 13:32 UTC, aduarteoutsystems reviewed
changed struture

2022-10-13 11:56 UTC, OS-johnkrug commented
Hi @JoaoPBatista . I think this one is good to go. Already approved by 2 OS people.

2022-10-14 15:37 UTC, merged